# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "users", :force => true do |t|
    t.column "password", :string
    t.column "bankroll", :integer
  end

  add_index "users", ["password"], :name => "users_password_index"

end
